name: Bug Report
description: 버그 발생
title: "[Bug Report]: "
body:
  - type: textarea
    attributes:
      label: Description
      description: 예상 동작은 무엇이고, 현재는 어떻게 작동하고 있나요?
      placeholder: 어떤 버그가 발생했는지 설명해주세요
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: 버그가 발생환 환경과 재현 방법을 알려주세요
    validations:
      required: true
  - type: textarea
    attributes:
      label: Tasks
      description: 해야할 일들을 적어주세요
      placeholder: checkbox를 이용해주세요
    validations:
      required: true
  - type: textarea
    attributes:
      label: Links
      description: 관련 링크를 첨부해주세요
  - type: checkboxes
    attributes:
      label: Assignees and Labels
      description: Assignee와 Labels를 추가해주세요
      options:
        - label: 모두 완료했습니다
          required: true
