name: Feature Request
description: 기능 요청사항을 입력해주세요
title: "[feature]: "
labels: ["feature", "frontent"]
assignees:
  - puranium235
body:
  - type: markdown
    attributes:
      value: 뭐라고 입력하면 될까요?
  - type: input
    id: contact
    attributes:
      label: label 요소
      description: description 요소
      placeholder: placeholder 요소
    validations:
      required: false
  - type: textarea
    id: what-happened
      label: id가 what happened입니다
      value: 미리 입력되어있는거 같음?
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: dropdown 메뉴
      multiple: true
      options:
        - 1번 메뉴
        - 2번 메뉴
        - 언제는 -를 쓰고 언제는 안쓰는겨
  - type: textarea
    id: logs
    attributes:
      label: log output
      description: copy and paste
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: ???
      description: agree
      options:
        - label: I agree
          required: true
