name: Feature Request
description: 기능 요청 또는 개선
title: "[feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes: 
      value: |
        최대한 쉽고 자세하게 입력해주세요!
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: 해야할 일들을 적어주세요
      placeholder: [ ] 사용자 기능 추가
    validations:
      required: true
