name: Feature Request
description: 기능 요청 또는 개선
title: "[feature]: "
labels: 
body:
  - type: markdown
    attributes: |
      최대한 쉽고 자세하게 입력해주세요!
  - type: textarea
    id: feature
    attributes:
      label: Description
      description: 어떤 기능이 왜 필요한지 설명해주세요!
      placeholder: 기능에 대한 설명
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: 대체 뭐가 불만이야 이놈은
      description: 해야할 일들을 적어주세요
      placeholder: [ ] 사용자 기능 추가
    validations:
      requitre: true
  - type: textarea
    id: more
    attributes:
      label: More
      description: 더 하고싶은 말이 있다면 작성해주세요
  - type: checkboxes
    id: labels
    attributes:
      label: Assignees and Labels
      description: Assignee와 Labels를 추가해주세요
      options:
        - label: 모두 완료했습니다
          required: true
