name: Refactor Request
description: 리팩터링 해야 할 부분
title: "[Refactor]: "
body:
  - type: textarea
    attributes:
      label: Description
      description: 어떤 부분을 왜 바꿔야하는지 설명해주세요
      placeholder: 리팩터링에 대한 설명
    validations:
      required: true
  - type: textarea
    attributes:
      label: Tasks
      description: 해야할 일들을 적어주세요
      placeholder: checkbox를 이용해주세요
    validations:
      required: true
        - type: textarea
    attributes:
      label: Links
      description: 관련 링크를 첨부해주세요
  - type: textarea
    attributes:
      label: More
      description: 더 하고싶은 말이 있다면 작성해주세요
  - type: checkboxes
    attributes:
      label: Assignees and Labels
      description: Assignee와 Labels를 추가해주세요
      options:
        - label: 모두 완료했습니다
          required: true
